#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2010: Sindre Røkenes Myren
#
# This file is part of KiKrit which is distributed under GPLv3. See the file
# COPYING.txt for more details.

import sys
import os

def main():
	try:
		from kikrit_server import settings
		PROJECT_ROOT = settings.PROJECT_ROOT
	except ImportError:
		settings = None
		PROJECT_ROOT = os.path.abspath(__file__).rsplit(os.path.sep, 2)[0]
		PROJECT_ROOT += os.path.sep + 'kikrit_server'

	if PROJECT_ROOT not in sys.path:
		sys.path.append(PROJECT_ROOT)

	if not settings:
		import settings

	from utils.kikrit_admin import execute_kikrit_admin
	execute_kikrit_admin(settings)


if __name__ == "__main__":
	main()
