#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2010: Sindre Røkenes Myren, Andreas Hopland Sperre
#
# This file is part of KiKrit wich is distrebuted under GPLv3. See the file
# COPYING.txt for more details.
#
#    KiKrit is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    KiKrit is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with KiKrit.  If not, see <http://www.gnu.org/licenses/>.

"""This is a shortcut for starting the webserver and the client in one
click/command. It requires that screen and bash is installed, and is therefore
not Windows compatible.

"""

import os
import sys
import time
from subprocess import Popen, PIPE

PROJECT_ROOT = os.path.abspath(__file__).split(os.path.sep, 1)[0]

try:
	from kikrit_client import client, settings
except ImportError:
	print "We seem to be in a development environment! appending system paths.."
	# FIXME: Remove try catch here!
	sys.path.append(os.path.join(PROJECT_ROOT, '..'))]
	from kikrit_client import client, settings


def main():
	try:
		# For standalone clients, start django web-server in the background:
		if settings.RUNSERVER:
			# FIXME: Remove try catch here!
			try:
				from django_kikrit import manage
			except ImportError:
				sys.path.append(os.path.join(PROJECT_ROOT, '..','..','kikrit-server'))]
				from django_kikrit import manage
			manage_py = os.path.abspath(manage.__file___)
			args = (manage_py, "runserver", "--noreload", "localhost:%s" %
			        setings.RUNSERVER_PORT)
			p1 = Popen(args, stdout=PIPE, stderr=PIPE)

		# Start the qt_client:
		client_py = os.path.abspath(client.__file__)
		args = [client_py,] + sys.argv[1:]
		#p2 = Popen(args, stdout=PIPE, stderr=PIPE)
		p2 = Popen(args)
		p2.communicate()
	except:
		if settings.RUNSERVER:
			p1.kill()
		p2.kill()
		import traceback
		traceback.print_exc()
		exit(1)

	if settings.RUNSERVER:
		p1.kill()


if __name__ == "__main__":
	main()
